name: php-app
services:
  app:
    image: php:8.1-fpm-alpine
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "3000:3000"
      - "443:443"
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/${ENVIRONMENT}/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
